version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: form_postgres
    restart: always
    environment:
      POSTGRES_USER: form_user
      POSTGRES_PASSWORD: form_pass
      POSTGRES_DB: form_db
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: